{
 "title": "Drupal Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "PHP VERSION",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "drupal_phpinfo_version" }
   ]
  },
  {
   "title": "CORE VERSION",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "drupal_update_status_core_version"
    }
   ]
  },
  {
   "title": "THEME VERSION",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "drupal_update_status_theme_version"
    }
   ]
  },
  {
   "title": "REVISION COUNT",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 9, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "drupal_revision_count_total" }
   ]
  },
  {
   "title": "NODE COUNT",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 2, "x": 11, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "drupal_node_count_total" }
   ]
  },
  {
   "title": "Drupal Modules Version",
   "type": "table",
   "gridPos": { "h": 14, "w": 13, "x": 0, "y": 5 },
   "targets": [
    {
     "expr": "drupal_update_status_module_version"
    }
   ]
  }
 ]
}