{
 "title": "Kubernetes Deployment metrics",
 "description": "Monitor web applications through cAdvisor and Prometheus client_ruby.",
 "tags": [ "app" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Node",
    "query": "label_values(kubernetes_io_hostname)"
   },
   {
    "name": "Namespace",
    "query": "label_values({namespace !~ \"default|kube-system|kube-public|.{0}\"}, namespace)"
   },
   {
    "name": "Deployment",
    "query": "label_values({namespace =~ \"$Namespace\", deployment =~ \".+\"}, deployment)"
   }
  ]
 },
 "panels": [
  {
   "title": "Replicas",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"^($Deployment).*$\",namespace=~\"^($Namespace).*$\"}) / sum(kube_deployment_status_replicas{deployment=~\"^($Deployment).*$\",namespace=~\"^($Namespace).*$\"}) * 100"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "cores" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"^($Deployment).*$\",namespace=~\"^($Namespace).*$\"}[5m])) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum (container_memory_working_set_bytes{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"^($Deployment).*$\",namespace=~\"^($Namespace).*$\"}) by (pod_name)",
     "legendFormat": "{{ pod_name }}"
    }
   ]
  },
  {
   "title": "Available",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"^($Deployment).*$\",namespace=~\"^($Namespace).*$\"})"
    }
   ]
  },
  {
   "title": "Total",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 2, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas{deployment=~\"^($Deployment).*$\",namespace=~\"^($Namespace).*$\"})"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_network_receive_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"^($Deployment).*$\",namespace=~\"^($Namespace).*$\"}[5m])) by (pod_name)",
     "legendFormat": "IN {{ pod_name }}"
    },
    {
     "expr": "- sum (rate (container_network_transmit_bytes_total{image!=\"\",name=~\"^k8s_.*\",pod_name=~\"^($Deployment).*$\",namespace=~\"^($Namespace).*$\"}[5m])) by (pod_name)",
     "legendFormat": "OUT {{ pod_name }}"
    }
   ]
  }
 ]
}